In [1]:
import numpy as np

In [2]:
#generates a numpy array
arr=np.array([[1,2,3,4,5]] , np.int64)

In [3]:
arr

array([[1, 2, 3, 4, 5]], dtype=int64)

In [4]:
arr[0]

array([1, 2, 3, 4, 5], dtype=int64)

In [5]:
#to change explicitly the value within array
arr[0, 2] = 8

In [6]:
#generates an array with temporarily wanted shape ( r,c )
arr.shape

(1, 5)

In [7]:
#declare the type of array elements are
arr.dtype

dtype('int64')

In [8]:
arr

array([[1, 2, 8, 4, 5]], dtype=int64)

In [9]:
#array creation
newarray=np.array([[1,2,3],[4,5,6],[7,8, 9]])

In [10]:
newarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#generate size of an array
newarray.size

9

In [12]:
newarray.dtype

dtype('int32')

In [13]:
newarray[0,0]=15

In [14]:
newarray

array([[15,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [15]:
newarray[0,0]=1

In [16]:
newarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
newarray.shape

(3, 3)

In [1]:
np.array({1,2,3})

NameError: name 'np' is not defined

In [19]:
#generates an array with elements zero's
zeros=np.zeros(5)

In [20]:
zeros

array([0., 0., 0., 0., 0.])

In [21]:
#array creation withing a range of number limit , here 15 is the limit--> less than 15 elemets are in the array
rangee= np.arange(15)

In [22]:
rangee

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
#generates an array with elements between the first 2 parameters but in the space of the 3 parameter
ls=np.linspace(1,4,13)

In [24]:
ls

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  ])

In [25]:
#generates an array of random values
emptyy=np.empty((3,4))

In [26]:
emptyy

array([[6.79699923e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [6.23053953e-307, 2.92966904e-033, 6.56087967e-091,
        1.88692632e+185],
       [2.38266511e+179, 1.54646706e-075, 3.99910963e+252,
        3.12015695e-033]])

In [27]:
#generates the identity matrix
ide=np.identity(10)

In [28]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
arrr=np.arange(50)

In [30]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [31]:
arrr.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
#generates any size of array to 1D array
arrr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [33]:
arrr.shape

(50,)

In [34]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
ar.resize(1,9)
ar

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
#generates the sum of all the elements present row wise and return an array
ar.sum(axis=1)

array([45])

In [37]:
#generates the sum of all the elemts present column wise and return an array
ar.sum(axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
ar=ar.transpose()
ar

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
ar.sum(axis=1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
ar.sum(axis=0)

array([45])

In [41]:
ar.ndim

2

In [42]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [43]:
#returns dimensions
ar.ndim

2

In [44]:
#return total number of bytes 
ar.nbytes

36

In [45]:
#generates size of array
ar.size

9

In [46]:
one=np.array([111,222,44,333,66] , np.int64)

In [47]:
#return the index of the max element
one.argmax()

3

In [48]:
#return the index of the min element
one.argmin()

2

In [49]:
#return the sorted index of the existing array elements
one.argsort()

array([2, 4, 0, 1, 3], dtype=int64)

In [50]:
narr=np.array([[1,2,3],[7,8,9],[4,5,6]])

In [51]:
narr

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [52]:
narr.argmax()

5

In [53]:
narr.argmin()

0

In [54]:
narr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [55]:
#return the max element's index wrt the individual column in array format
narr.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [56]:
#return the max element's index wrt the individual row in array format
narr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [57]:
narr.argsort(axis=0)

array([[0, 0, 0],
       [2, 2, 2],
       [1, 1, 1]], dtype=int64)

In [58]:
narr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [59]:
 np.where(narr>7)

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [60]:
import sys

In [61]:
lst=[1,2,3,4,5]

In [62]:
np_lst=np.array([1,2,3,4,5])

In [63]:
#to get size of a python list
sys.getsizeof(1)*len(lst)

140

In [64]:
#to calculate size of a numpy array
np_lst.itemsize * np_lst.size

20

In [65]:
#generate an array consists of only one's
abcd=np.ones((2,4))

In [66]:
abcd

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
#generates an array with given size with exact number of multiple digits as elements
np.full((3,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [68]:
#generate the exact number multiple times in the existing array
np.full_like(abcd,9)

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [69]:
#generate random values in range ()
ran=np.random.rand(4,5)

In [70]:
ran

array([[0.00880803, 0.1089857 , 0.0766423 , 0.02444043, 0.65097359],
       [0.87110524, 0.65530282, 0.88198716, 0.90833087, 0.08561128],
       [0.29336919, 0.68367712, 0.67336825, 0.16683029, 0.33962673],
       [0.05402422, 0.55299115, 0.99185893, 0.15278107, 0.81353436]])

In [71]:
ran[2,3]=5

In [72]:
ran

array([[0.00880803, 0.1089857 , 0.0766423 , 0.02444043, 0.65097359],
       [0.87110524, 0.65530282, 0.88198716, 0.90833087, 0.08561128],
       [0.29336919, 0.68367712, 0.67336825, 5.        , 0.33962673],
       [0.05402422, 0.55299115, 0.99185893, 0.15278107, 0.81353436]])

In [73]:
#enerate random values in range with given dimensions
np.random.randint(8,size=(2,3))

array([[2, 5, 1],
       [6, 2, 0]])

In [74]:
#generate an array with repeated row or column values according to choice
arrayy=np.array([[1,2,3,4]])
arrayy.repeat(3,axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [75]:
#generated random pattern
ones=np.full((5,5),2)
print(ones)
ze=np.ones((3,3))
print(ze)
ze[1,1]=0
print(ze)
ones[1:-1,1:-1]=ze
print(ones)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
[[2 2 2 2 2]
 [2 1 1 1 2]
 [2 1 0 1 2]
 [2 1 1 1 2]
 [2 2 2 2 2]]


##### BE CAREFUL WHILE DEALING WITH ARRAY IN TERMS OF COPYING !!!!

In [76]:
eg1=np.array([1,2,3,4])
#eg2=eg1
eg2=eg1.copy()
eg2[1]=5
print(eg2)
print(eg1)

[1 5 3 4]
[1 2 3 4]


# Mathematics Operations

In [77]:
arra=np.array([1,2,3,4])
arra+3

array([4, 5, 6, 7])

In [78]:
arra-4

array([-3, -2, -1,  0])

In [79]:
arra/2

array([0.5, 1. , 1.5, 2. ])

In [80]:
arra*5

array([ 5, 10, 15, 20])

In [81]:
#generates an array which contains elemet that are the individial element sum of the two arrays 
arrb=np.array([5,6,7,8])
arrc=arra+arrb
arrc

array([ 6,  8, 10, 12])

In [82]:
arrc**2

array([ 36,  64, 100, 144], dtype=int32)

In [83]:
np.sin(arra)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [84]:
np.cos(arra)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [85]:
np.tan(arra)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

# Linear Algebra

In [86]:
#used to multiply the arrays 
ones=np.ones((2,3))
seno=np.full((3,2),4)
np.matmul(ones,seno)

array([[12., 12.],
       [12., 12.]])

In [87]:
ide=np.identity(6)

In [88]:
#finds the determinant
np.linalg.det(ide)

1.0

In [89]:
#find the trace-->sum of the diagonal elements
ide.trace()

6.0

In [90]:
matrix=np.matrix('[1,2,3,4]')
matrix

matrix([[1, 2, 3, 4]])

In [91]:
np.linalg.svd(matrix)

(matrix([[-1.]]),
 array([5.47722558]),
 matrix([[-0.18257419, -0.36514837, -0.54772256, -0.73029674],
         [-0.36514837,  0.88725161, -0.16912258, -0.22549678],
         [-0.54772256, -0.16912258,  0.74631613, -0.33824516],
         [-0.73029674, -0.22549678, -0.33824516,  0.54900645]]))

In [92]:
#generates eigen values

In [93]:
#generates inverse of matrix

In [94]:
#generates matrix norm

# Statistics

In [95]:
stat=np.array([[1,2,3,4],[5,6,7,8]])
stat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
np.min(stat)
np.min(stat,axis=1)

array([1, 5])

In [97]:
np.max(stat)
np.max(stat, axis=1)

array([4, 8])

In [98]:
np.sum(stat)
np.sum(stat,axis=1)

array([10, 26])

In [99]:
np.median(stat)

4.5

In [100]:
np.mean(stat)

4.5

# File Functions

In [101]:
fileData=np.genfromtxt('Test14jul.txt',delimiter=',') #delimiter=separator
fileData

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]])

In [102]:
fileData=fileData.astype('int32') #can change the type of data in the file 
fileData

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

##### Advance Indexing !!

In [103]:
((fileData<=np.median(fileData))&(fileData<26)) #check the values which are greater than median of the fileData 

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [104]:
fileData[fileData<=np.median(fileData)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [105]:
#index with a list in numpy
data=np.array([1,2,3,4,5,6,7,8])
data[[3,6,1,4]]

array([4, 7, 2, 5])

In [106]:
np.any(fileData<=np.median(fileData),axis=1) #finds the value of present row wise and return boolean value accordingly 

array([ True,  True,  True, False, False])

In [107]:
(~((fileData<=np.median(fileData))&(fileData<26)))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [110]:
mat=np.arange(1,31)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [112]:
mat.resize(5,6)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [117]:
mat[[1,2,3,4],[0,1,2,3]]

array([ 7, 14, 21, 28])

In [125]:
mat[2:4,2:4] # mat(r,c)

array([[15, 16],
       [21, 22]])